import type { PreferenceDefinition, BirthType, BirthVenue } from './editorTypes'

export const PREFERENCES: PreferenceDefinition[] = [
  // ============================================
  // PRE-HOSPITAL ARRIVAL
  // ============================================
  {
    id: 'when_to_hospital',
    sectionId: 'pre_hospital',
    title: 'When to Go to Hospital',
    description: 'What are your preferences for timing of arrival?',
    icon: 'Clock',
    allowCustom: true,
    hiddenForVenue: ['home', 'birth_center'],
    quizQuestionId: 'when_to_hospital',
    options: [
      { value: 'active_labor_4_5', label: 'Active labor (contractions 4-5 min apart)', birthPlanText: 'We plan to arrive when contractions are 4-5 minutes apart, lasting about 1 minute each.', isPopular: true },
      { value: 'active_labor_3_1_1', label: 'Active labor (contractions 3 min apart, emotional signposts)', birthPlanText: 'We plan to arrive when contractions are 3 minutes apart, lasting 1 minute, for at least 1 hour, and I am exhibiting the emotional signposts of active labor.', isPopular: true },
      { value: 'water_breaks', label: 'If my water breaks', birthPlanText: 'We will head to the hospital if my water breaks.' },
      { value: 'early', label: 'Arrive early for monitoring', birthPlanText: 'We prefer to arrive early for monitoring, support, and/or for a medical reason (such as GBS antibiotics).' },
      { value: 'provider_guidance', label: 'Follow our provider\'s guidance', birthPlanText: 'We will call our provider and arrive when they recommend.' },
    ],
  },
  {
    id: 'when_to_birth_center',
    sectionId: 'pre_hospital',
    title: 'When to Go to the Birth Center',
    description: 'When do you plan to head to the birth center?',
    icon: 'Clock',
    allowCustom: true,
    venueOnly: ['birth_center'],
    quizQuestionId: 'when_to_birth_center',
    options: [
      { value: 'active_labor', label: 'When contractions are regular and close together', birthPlanText: 'We plan to go to the birth center when contractions are regular and close together.', isPopular: true },
      { value: 'emotional_signposts', label: 'When I can no longer talk through contractions', birthPlanText: 'We will head to the birth center when I can no longer talk through contractions.', isPopular: true },
      { value: 'water_breaks', label: 'If my water breaks', birthPlanText: 'We will go to the birth center if my water breaks.' },
      { value: 'provider_guidance', label: 'When our midwife/provider advises', birthPlanText: 'We will follow our midwife\'s guidance on when to come to the birth center.' },
      { value: 'gbs_antibiotics', label: 'Early, for GBS antibiotics or other medical reason', birthPlanText: 'We will arrive early if needed for GBS antibiotics or other medical reasons.' },
    ],
  },
  {
    id: 'when_to_call_midwife',
    sectionId: 'pre_hospital',
    title: 'When to Call Your Midwife',
    description: 'When will you call your midwife to come to your home?',
    icon: 'Clock',
    allowCustom: true,
    venueOnly: ['home'],
    quizQuestionId: 'when_to_call_midwife',
    options: [
      { value: 'active_labor', label: 'When contractions are regular and close together', birthPlanText: 'We will call our midwife when contractions are regular and close together.', isPopular: true },
      { value: 'emotional_signposts', label: 'When I feel I need my midwife\'s support', birthPlanText: 'We will call our midwife when I feel I need her support.', isPopular: true },
      { value: 'water_breaks', label: 'If my water breaks', birthPlanText: 'We will call our midwife if my water breaks.' },
      { value: 'early_labor_support', label: 'During early labor for reassurance', birthPlanText: 'We would like our midwife to come during early labor for reassurance.' },
      { value: 'provider_guidance', label: 'When my midwife advises based on check-ins', birthPlanText: 'We will follow our midwife\'s guidance based on phone check-ins.' },
    ],
  },
  {
    id: 'labor_start_preference',
    sectionId: 'pre_hospital',
    title: 'How Labor Starts',
    description: 'Preferences for labor onset methods',
    icon: 'Clock',
    allowCustom: true,
    clinical: true,
    quizQuestionId: 'labor_start',
    options: [
      { value: 'wait_natural', label: 'Wait for labor to start naturally', birthPlanText: 'We prefer to wait for labor to begin naturally.' },
      { value: 'nipple_stimulation', label: 'Try nipple stimulation', birthPlanText: 'We are open to nipple stimulation as a natural method to encourage labor.' },
      { value: 'membrane_sweep', label: 'Membrane sweep', birthPlanText: 'We are open to a membrane sweep if recommended by our provider.' },
      { value: 'natural_methods', label: 'Natural methods', birthPlanText: 'We plan to try natural methods to encourage labor.' },
      { value: 'amniotomy', label: 'Amniotomy', birthPlanText: 'We are open to amniotomy to help start or progress labor.' },
      { value: 'pitocin_induction', label: 'Pitocin if medically needed', birthPlanText: 'We are open to Pitocin induction if medically indicated.' },
    ],
  },
  {
    id: 'communication_preferences',
    sectionId: 'pre_hospital',
    title: 'Communication Preferences',
    description: 'How you want the medical team to communicate with you',
    icon: 'MessageSquare',
    allowCustom: true,
    options: [
      { value: 'explain_before', label: 'Explain all procedures before performing', birthPlanText: 'Please explain all procedures before performing them and give us time to ask questions.' },
      { value: 'ask_consent', label: 'Ask consent before any intervention', birthPlanText: 'Please ask our consent before any intervention or procedure.' },
      { value: 'preferred_name', label: 'Use our preferred names', birthPlanText: 'Please use our preferred names when addressing us.' },
      { value: 'standard_fine', label: 'Standard communication is fine', birthPlanText: '' },
    ],
  },
  {
    id: 'pet_care_plan',
    sectionId: 'pre_hospital',
    title: 'Pet Care Plan',
    description: 'Arrangements for your pets while you are away for birth',
    icon: 'Heart',
    allowCustom: true,
    isOmittedByDefault: true,
    options: [
      { value: 'neighbor', label: 'Neighbor will care for pets', birthPlanText: 'Our neighbor will care for our pets while we are away.' },
      { value: 'auto_feeder', label: 'Pets staying home alone (auto-feeder set up)', birthPlanText: 'Our pets will stay home alone with automatic feeders set up.' },
      { value: 'family', label: 'Family member taking pets', birthPlanText: 'A family member will take care of our pets.' },
    ],
  },
  {
    id: 'child_care_plan',
    sectionId: 'pre_hospital',
    title: 'Child Care Plan',
    description: 'Arrangements for older children during labor and birth',
    icon: 'Users',
    allowCustom: true,
    isOmittedByDefault: true,
    options: [
      { value: 'grandparent', label: 'Grandparent picking up older child(ren)', birthPlanText: 'A grandparent will pick up and care for our older child(ren).' },
      { value: 'neighbor', label: 'Neighbor or friend taking kids', birthPlanText: 'A neighbor or friend will care for our older child(ren).' },
      { value: 'coming_along', label: 'Kids coming to birth location', birthPlanText: 'Our older child(ren) will be present at the birth.' },
    ],
  },
  {
    id: 'birth_space',
    sectionId: 'pre_hospital',
    title: 'Birth Space Setup',
    description: 'How you want your home birth environment set up',
    icon: 'Home',
    allowCustom: true,
    venueOnly: ['home'],
    quizQuestionId: 'birth_space_setup',
    options: [
      { value: 'dim_lighting', label: 'Dim, calm lighting', birthPlanText: 'We want dim, calm lighting in our birth space.' },
      { value: 'music', label: 'Music or playlist', birthPlanText: 'We plan to have calming music or a playlist during labor.' },
      { value: 'aromatherapy', label: 'Aromatherapy', birthPlanText: 'We plan to use aromatherapy during labor.' },
      { value: 'minimal_people', label: 'Minimal people present', birthPlanText: 'We prefer only essential people in the birth room during labor and delivery.' },
    ],
  },
  {
    id: 'admission_procedures',
    sectionId: 'during_labor',
    title: 'Admission Procedures',
    description: 'Preferences for hospital admission process',
    icon: 'BookOpen',
    allowCustom: true,
    options: [
      { value: 'minimize', label: 'Minimize procedures', birthPlanText: 'Please minimize admission procedures to allow focus on labor.', isPopular: true },
      { value: 'standard', label: 'Standard admission', birthPlanText: 'Standard admission procedures are acceptable.' },
      { value: 'discuss', label: 'Discuss each procedure', birthPlanText: 'Please discuss each admission procedure with us before proceeding.' },
    ],
  },
  {
    id: 'photography_video',
    sectionId: 'during_labor',
    title: 'Photography & Video',
    description: 'Plans for documenting the birth',
    icon: 'Camera',
    allowCustom: true,
    options: [
      { value: 'professional', label: 'Professional birth photographer', birthPlanText: 'We have hired a professional birth photographer who will be present.', isPopular: true },
      { value: 'partner', label: 'Partner will take photos', birthPlanText: 'My partner will take photos during labor and birth.' },
      { value: 'video', label: 'Video recording', birthPlanText: 'We plan to record video during the birth.' },
      { value: 'none', label: 'No photos or video', birthPlanText: 'We prefer no photography or video.' },
    ],
  },
  {
    id: 'limited_interruptions',
    sectionId: 'during_labor',
    title: 'Interruptions During Labor',
    description: 'Preferences for staff visits and monitoring',
    icon: 'AlertCircle',
    allowCustom: true,
    options: [
      { value: 'minimal', label: 'Prefer minimal disruptions', birthPlanText: 'We prefer limited interruptions during labor to allow focus and rest.', isPopular: true },
      { value: 'standard', label: 'Standard monitoring okay', birthPlanText: 'Standard monitoring and check-ins are acceptable.' },
    ],
  },
  {
    id: 'quiet_labor_environment',
    sectionId: 'during_labor',
    title: 'Quiet Environment',
    description: 'Atmosphere preferences during labor',
    icon: 'Moon',
    allowCustom: true,
    options: [
      { value: 'quiet', label: 'Dim lights/quiet voices preferred', birthPlanText: 'We prefer dim lights and quiet voices during labor.', isPopular: true },
      { value: 'no_preference', label: 'No preference', birthPlanText: 'Standard hospital environment is fine.' },
    ],
  },

  // ============================================
  // DURING LABOR
  // ============================================
  {
    id: 'pain_management',
    sectionId: 'during_labor',
    title: 'Pain Management',
    description: 'An epidural is regional anesthesia that blocks pain in the lower body while allowing you to remain awake and alert. It provides effective pain relief but may limit your ability to move and can lengthen labor. Unmedicated birth allows full mobility and often results in shorter recovery time. Nitrous oxide (laughing gas) takes the edge off pain while maintaining mobility. There\'s no "right" choice - some people plan ahead, while others prefer to decide in the moment based on how labor progresses.',
    icon: 'Heart',
    allowCustom: true,
    quizQuestionId: 'pain_approach',
    options: [
      { value: 'natural', label: 'Planning unmedicated birth', birthPlanText: 'We are planning an unmedicated birth. Please do not offer pain medication unless I ask for it.', isPopular: true, icon: 'Heart' },
      { value: 'open', label: 'Open to options, will decide in the moment', birthPlanText: 'We are open to pain management options and will decide during labor.', isPopular: true, icon: 'AlertCircle' },
      { value: 'epidural', label: 'Planning to get an epidural', birthPlanText: 'We plan to request an epidural during labor.', icon: 'Syringe' },
      { value: 'nitrous', label: 'Planning to use nitrous oxide', birthPlanText: 'We plan to utilize nitrous oxide to help with pain management.', icon: 'Wind' },
      { value: 'iv_meds', label: 'IV pain medication (fentanyl, etc.)', birthPlanText: 'We are open to IV pain medication if needed during labor.', icon: 'Droplets' },
      { value: 'water', label: 'Warm water (shower/tub)', birthPlanText: 'We plan to use warm water immersion (shower or tub) for pain relief.', icon: 'Bath' },
      { value: 'breathing', label: 'Breathing and relaxation techniques', birthPlanText: 'We plan to use breathing and relaxation techniques for pain management.', icon: 'Wind' },
      { value: 'massage', label: 'Massage and counterpressure', birthPlanText: 'We plan to use massage and counterpressure techniques during labor.', icon: 'HandMetal' },
      { value: 'hypnobirthing', label: 'HypnoBirthing / self-hypnosis', birthPlanText: 'We have trained in HypnoBirthing techniques and plan to use them during labor.', icon: 'Brain' },
      { value: 'bradley', label: 'Bradley Method', birthPlanText: 'We have trained in the Bradley Method and plan to use it during labor.', icon: 'HeartHandshake' },
    ],
  },
  {
    id: 'fetal_monitoring',
    sectionId: 'during_labor',
    title: 'Fetal Monitoring',
    description: 'Fetal monitoring tracks your baby\'s heart rate during labor. Continuous monitoring keeps you connected to a machine throughout labor, which can limit movement but provides constant data. Intermittent monitoring checks baby\'s heart rate every 15-30 minutes using a handheld doppler, allowing you to move freely, use the shower, and change positions. For low-risk pregnancies, research shows intermittent monitoring is just as safe as continuous monitoring and may lead to fewer interventions.',
    icon: 'Activity',
    allowCustom: true,
    quizQuestionId: 'fetal_monitoring',
    options: [
      { value: 'intermittent', label: 'Intermittent (checked periodically)', birthPlanText: 'We prefer intermittent fetal monitoring to allow freedom of movement.', isPopular: true },
      { value: 'wireless', label: 'Wireless/waterproof if available', birthPlanText: 'If continuous monitoring is needed, we prefer wireless or waterproof monitors so movement is not impeded.', isPopular: true },
      { value: 'continuous', label: 'Continuous monitoring is fine', birthPlanText: 'We are comfortable with continuous fetal monitoring, even if it restricts movement.' },
    ],
  },
  {
    id: 'iv_preference',
    sectionId: 'during_labor',
    title: 'IV vs Hep Lock',
    description: 'Preference for IV access during labor',
    icon: 'Syringe',
    allowCustom: true,
    hiddenForVenue: ['home'],
    options: [
      { value: 'heplock', label: 'Hep lock only (IV ready, no fluids)', birthPlanText: 'We prefer a hep lock instead of continuous IV fluids.', isPopular: true },
      { value: 'iv', label: 'Continuous IV is fine', birthPlanText: 'Continuous IV fluids are acceptable.' },
      { value: 'neither', label: 'No IV access initially or until an IV is needed', birthPlanText: 'We prefer no IV access initially, or until an IV is needed.' },
    ],
  },
  {
    id: 'eating_drinking',
    sectionId: 'during_labor',
    title: 'Eating & Drinking',
    description: 'Food and beverage during labor',
    icon: 'Coffee',
    allowCustom: true,

    options: [
      { value: 'yes', label: 'Eat and drink freely', birthPlanText: 'I plan to eat and drink as desired during labor.', isPopular: true },
      { value: 'clear_liquids', label: 'Clear liquids only is fine', birthPlanText: 'I plan to drink clear liquids as desired.' },
      { value: 'follow_policy', label: 'Follow hospital policy', birthPlanText: 'We will follow hospital policy regarding eating and drinking.' },
    ],
  },
  {
    id: 'movement_positions',
    sectionId: 'during_labor',
    title: 'Movement & Positioning',
    description: 'Freedom to move and change positions',
    icon: 'Move',
    allowCustom: true,
    hiddenFor: ['planned_csection'],
    quizQuestionId: 'movement_labor',
    options: [
      { value: 'freedom', label: 'Very important - I want full freedom', birthPlanText: 'Freedom to move, walk, and change positions during labor is very important to us.', isPopular: true },
      { value: 'upright', label: 'I\'d like to, but I\'m flexible', birthPlanText: 'We would prefer freedom to move during labor but are flexible based on circumstances.', isPopular: true },
      { value: 'bed', label: 'Not a priority for me', birthPlanText: 'Mobility during labor is not a priority for us.' },
    ],
  },
  {
    id: 'hydrotherapy',
    sectionId: 'during_labor',
    title: 'Hydrotherapy',
    description: 'Use of water for pain relief',
    icon: 'Droplet',
    allowCustom: true,
    hiddenFor: ['planned_csection'],
    options: [
      { value: 'tub', label: 'Want to use tub/pool', birthPlanText: 'I would like to use a tub or birthing pool during labor.', isPopular: true },
      { value: 'shower', label: 'Shower available', birthPlanText: 'I may use the shower for pain relief.' },
      { value: 'water_birth', label: 'Plan to deliver in water (water birth)', birthPlanText: 'We are planning a water birth - delivering baby in the tub.' },
      { value: 'not_interested', label: 'Not planning to use', birthPlanText: 'We are not planning to use hydrotherapy.' },
    ],
  },
  {
    id: 'labor_environment',
    sectionId: 'during_labor',
    title: 'Labor Environment',
    description: 'Setting the atmosphere during labor',
    icon: 'Lightbulb',
    allowCustom: true,
    options: [
      { value: 'dim_quiet', label: 'Dim lighting and quiet', birthPlanText: 'We prefer dim lighting, a quiet environment, and minimal interruptions / check-ins from hospital staff.', isPopular: true },
      { value: 'music', label: 'We\'ll bring our own music', birthPlanText: 'We will bring our own music to play during labor.', isPopular: true },
      { value: 'aromatherapy', label: 'Aromatherapy and calming touches', birthPlanText: 'We would like to use aromatherapy during labor.' },
      { value: 'standard', label: 'Standard hospital environment', birthPlanText: 'Standard hospital environment is fine.' },
    ],
  },
  {
    id: 'medical_students',
    sectionId: 'during_labor',
    title: 'Medical Students & Observers',
    description: 'Preference for students or residents observing your birth',
    icon: 'GraduationCap',
    allowCustom: true,
    clinical: true,
    hiddenForVenue: ['home', 'birth_center'],
    quizQuestionId: 'medical_students',
    options: [
      { value: 'welcome', label: 'Students are welcome to observe', birthPlanText: 'We are comfortable with medical students or residents observing.', isPopular: true },
      { value: 'prefer_not', label: 'We prefer no students or observers', birthPlanText: 'We prefer that no medical students or residents observe or participate in our care.' },
      { value: 'ask_first', label: 'Ask us first each time', birthPlanText: 'Please ask our permission before any students or observers enter the room.', isPopular: true, defaultStance: 'cautious' },
    ],
  },
  {
    id: 'gbs_antibiotics',
    sectionId: 'during_labor',
    title: 'GBS Antibiotics',
    description: 'Preference if tested positive for Group B Strep',
    icon: 'Pill',
    allowCustom: true,
    clinical: true,

    options: [
      { value: 'accept', label: 'Accept antibiotics if GBS positive', birthPlanText: 'Please administer IV antibiotics as recommended.', isPopular: true, defaultStance: 'desired' },
      { value: 'decline', label: 'Decline antibiotics', birthPlanText: 'We decline GBS antibiotics and accept responsibility for this decision.', defaultStance: 'declined' },
      { value: 'natural', label: 'Discuss alternative approaches', birthPlanText: 'We would like to discuss alternative protocols for GBS.', defaultStance: 'cautious' },
    ],
  },
  {
    id: 'pushing_position',
    sectionId: 'during_labor',
    title: 'Pushing Positions',
    description: 'Preferred positions for the pushing stage',
    icon: 'Navigation',
    allowCustom: true,
    hiddenFor: ['planned_csection'],

    options: [
      { value: 'freedom', label: 'Freedom to choose in the moment', birthPlanText: 'I would like the freedom to push in different positions as feels natural.', isPopular: true },
      { value: 'standard', label: 'Standard position (lying on back) is fine', birthPlanText: 'Standard pushing position (lying on back) is acceptable.' },
    ],
  },
  {
    id: 'directed_pushing',
    sectionId: 'during_labor',
    title: 'Directed vs Spontaneous Pushing',
    description: 'Directed pushing involves coached breath-holding and pushing with counting (often "purple pushing"). Spontaneous pushing means following your body\'s natural urges to push, which often results in shorter pushes with more frequent breaks. Research suggests that spontaneous pushing may reduce the risk of perineal tearing and fetal distress, while directed pushing can be helpful if you have an epidural and can\'t feel the urge to push clearly. Many care providers now encourage a hybrid approach, using your instincts when possible but offering guidance if needed.',
    icon: 'Wind',
    allowCustom: true,
    hiddenFor: ['planned_csection'],

    options: [
      { value: 'spontaneous', label: 'Spontaneous pushing', birthPlanText: 'I prefer to push spontaneously, following my body\'s natural urges rather than coached counting.', isPopular: true },
      { value: 'directed', label: 'Directed/coached pushing', birthPlanText: 'I would like coached, directed pushing with counting.' },
      { value: 'flexible', label: 'Flexible approach', birthPlanText: 'I am open to either directed or spontaneous pushing depending on what feels right.' },
    ],
  },
  {
    id: 'perineal_support',
    sectionId: 'during_labor',
    title: 'Perineal Support & Tearing',
    description: 'Preferences for preventing tearing',
    icon: 'Shield',
    allowCustom: true,
    hiddenFor: ['planned_csection'],

    options: [
      { value: 'natural', label: 'Natural stretching', birthPlanText: 'I prefer to allow natural stretching and avoid episiotomy unless absolutely necessary.', isPopular: true },
      { value: 'support', label: 'Warm compresses & massage', birthPlanText: 'Please use warm compresses and perineal massage to help prevent tearing.', isPopular: true },
      { value: 'episiotomy_if_needed', label: 'Episiotomy if recommended', birthPlanText: 'I trust my provider to recommend episiotomy if medically beneficial.' },
    ],
  },
  {
    id: 'labor_augmentation',
    sectionId: 'during_labor',
    title: 'If Labor Slows Down',
    description: 'Preferences for augmentation if labor stalls',
    icon: 'Activity',
    allowCustom: true,
    clinical: true,
    quizQuestionId: 'labor_augmentation',
    options: [
      { value: 'nipple_stimulation', label: 'Nipple stimulation', birthPlanText: 'If labor slows, we would like to try nipple stimulation to encourage contractions.' },
      { value: 'position_changes', label: 'Position changes and movement', birthPlanText: 'If labor slows, we would like to try position changes and movement to encourage progress.' },
      { value: 'hydrotherapy', label: 'Warm bath or shower', birthPlanText: 'If labor slows, we would like to try a warm bath or shower to encourage progress.' },
      { value: 'rest_eat', label: 'Rest, eat, and hydrate', birthPlanText: 'If labor slows, we would like to rest, eat, and hydrate before trying other interventions.' },
      { value: 'acupressure', label: 'Acupressure or massage', birthPlanText: 'If labor slows, we would like to try acupressure or massage to encourage contractions.' },
      { value: 'wait_it_out', label: 'Try natural methods first', birthPlanText: 'If labor slows, we prefer to try natural methods first before considering Pitocin.' },
      { value: 'low_dose_pitocin', label: 'Pitocin at lowest dose', birthPlanText: 'If augmentation is needed, we prefer Pitocin at the lowest effective dose with slow increases.' },
      { value: 'pitocin_stop_active', label: 'Pitocin but turn off at active labor', birthPlanText: 'If Pitocin is used, we would like it reduced or stopped once active labor is established.' },
      { value: 'provider_recommends', label: 'Provider\'s recommendation', birthPlanText: 'We trust our provider\'s judgment on augmentation if labor stalls.' },
    ],
  },
  {
    id: 'cervical_checks',
    sectionId: 'during_labor',
    title: 'Cervical Checks',
    description: 'Preferences for vaginal exams during labor',
    icon: 'Shield',
    allowCustom: true,
    clinical: true,
    quizQuestionId: 'cervical_checks',
    options: [
      { value: 'minimize', label: 'Minimize checks', birthPlanText: 'Please minimize cervical exams - only when clinically necessary.' },
      { value: 'only_requested', label: 'Only when I request', birthPlanText: 'Please only perform cervical checks when I ask for one.' },
      { value: 'no_after_water', label: 'Decline after water breaks', birthPlanText: 'Please do not perform vaginal exams after my water has broken.' },
      { value: 'routine_fine', label: 'Routine checks fine', birthPlanText: 'Routine cervical checks during labor are fine with us.' },
      { value: 'consent_each', label: 'Ask before each', birthPlanText: 'Please ask my permission before each cervical exam.' },
      { value: 'no_checks', label: 'No cervical checks', birthPlanText: 'I decline all cervical checks unless I specifically request one.' },
    ],
  },
  {
    id: 'episiotomy',
    sectionId: 'during_labor',
    title: 'Episiotomy',
    description: 'Preferences regarding episiotomy during delivery',
    icon: 'Scissors',
    allowCustom: true,
    clinical: true,
    quizQuestionId: 'episiotomy',
    options: [
      { value: 'avoid', label: 'Prefer to avoid', birthPlanText: 'We prefer to avoid episiotomy. Please use perineal massage and warm compresses instead.', defaultStance: 'declined' },
      { value: 'only_consent', label: 'Only with consent', birthPlanText: 'Please do not perform an episiotomy without discussing it with us first.', defaultStance: 'cautious' },
      { value: 'prevent_upward_tear', label: 'Only if necessary to prevent an upward (clitoral/urethral) tear', birthPlanText: 'If I am about to tear upward toward the clitoris or urethra, I consent to an episiotomy to redirect tearing.' },
      { value: 'provider_judgment', label: 'Provider\'s judgment', birthPlanText: 'We are open to episiotomy if our provider determines it is necessary.', defaultStance: 'desired' },
    ],
  },
  {
    id: 'assisted_delivery',
    sectionId: 'during_labor',
    title: 'Assisted Delivery (Forceps/Vacuum)',
    description: 'Preferences if pushing assistance is needed',
    icon: 'Activity',
    allowCustom: true,
    clinical: true,
    options: [
      { value: 'prefer_vacuum', label: 'Prefer vacuum over forceps', birthPlanText: 'If assisted delivery is needed, we prefer vacuum extraction over forceps.', defaultStance: 'cautious' },
      { value: 'discuss_first', label: 'Discuss alternatives first', birthPlanText: 'Before assisted delivery, please try position changes and give us time. Discuss options with us.', defaultStance: 'cautious' },
      { value: 'provider_recommendation', label: 'Provider\'s recommendation', birthPlanText: 'We trust our provider\'s judgment on assisted delivery if needed.', defaultStance: 'desired' },
      { value: 'prefer_avoid', label: 'Prefer to avoid', birthPlanText: 'We prefer to avoid forceps and vacuum extraction if possible.', defaultStance: 'declined' },
    ],
  },
  {
    id: 'birthing_equipment',
    sectionId: 'during_labor',
    title: 'Birthing Equipment Requests',
    description: 'Specific equipment you want available during labor',
    icon: 'Move',
    allowCustom: true,
    options: [
      { value: 'birthing_ball', label: 'Birthing ball', birthPlanText: 'Please have a birthing ball available.' },
      { value: 'squat_bar', label: 'Squat bar', birthPlanText: 'Please have a squat bar available for pushing.' },
      { value: 'peanut_ball', label: 'Peanut ball', birthPlanText: 'Please have a peanut ball available.' },
      { value: 'birthing_stool', label: 'Birthing stool', birthPlanText: 'Please have a birthing stool available.' },
      { value: 'rebozo', label: 'Rebozo', birthPlanText: 'We will be bringing a rebozo for labor support.' },
    ],
  },
  {
    id: 'water_birth',
    sectionId: 'during_labor',
    title: 'Water Birth',
    description: 'Whether to use water immersion during labor or for delivery',
    icon: 'Waves',
    allowCustom: true,
    quizQuestionId: 'water_birth',
    options: [
      { value: 'water_birth', label: 'Planning a water birth', birthPlanText: 'We are planning a water birth and would like to deliver in the tub/pool.', isPopular: true },
      { value: 'water_labor', label: 'Water for labor only (deliver outside of tub)', birthPlanText: 'We would like to use the tub/pool for labor comfort but plan to deliver outside of the tub.' },
      { value: 'no_water', label: 'Not using water', birthPlanText: '' },
    ],
  },
  {
    id: 'vbac_monitoring',
    sectionId: 'during_labor',
    title: 'VBAC Monitoring',
    description: 'Fetal monitoring preferences specific to VBAC labor',
    icon: 'Activity',
    allowCustom: true,
    quizQuestionId: 'vbac_monitoring',
    options: [
      { value: 'continuous_wireless', label: 'Continuous wireless monitor', birthPlanText: 'We accept continuous fetal monitoring for VBAC and request a wireless/waterproof monitor to allow mobility.', isPopular: true },
      { value: 'continuous_standard', label: 'Continuous standard monitor', birthPlanText: 'We accept continuous fetal monitoring during our VBAC labor.' },
      { value: 'intermittent_request', label: 'Request intermittent (discuss with provider)', birthPlanText: 'We would like to discuss intermittent monitoring options for our VBAC with our provider.' },
    ],
  },
  {
    id: 'birth_mirror',
    sectionId: 'at_birth',
    title: 'Mirror to See Baby Emerge',
    description: 'Watching baby being born',
    icon: 'Eye',
    allowCustom: true,
    hiddenFor: ['planned_csection'],
    options: [
      { value: 'yes', label: 'Yes please', birthPlanText: 'I would like a mirror so I can see baby emerge.', isPopular: true },
      { value: 'no', label: 'No thank you', birthPlanText: 'I prefer not to use a mirror during delivery.' },
    ],
  },
  {
    id: 'unplanned_csection',
    sectionId: 'csection',
    title: 'Unplanned C-Section Preferences',
    description: 'If cesarean becomes necessary',
    icon: 'AlertCircle',
    allowCustom: true,

    options: [
      { value: 'gentle', label: 'Request gentle C-section', birthPlanText: 'If a C-section becomes necessary, we would like gentle/family-centered techniques when safely possible (clear drape, skin-to-skin in OR, etc.).', isPopular: true },
      { value: 'partner_present', label: 'Partner must be present', birthPlanText: 'If a C-section is needed, it is very important that my partner be present.' },
      { value: 'standard', label: 'Standard protocol', birthPlanText: 'If a C-section becomes necessary, please follow standard hospital protocol.' },
      { value: 'discuss', label: 'Discuss all options first', birthPlanText: 'If a C-section becomes necessary, please discuss all available options with us.' },
    ],
  },

  // ============================================
  // AT & IMMEDIATELY AFTER BIRTH
  // ============================================
  {
    id: 'skin_to_skin',
    sectionId: 'at_birth',
    title: 'Immediate Skin-to-Skin',
    description: 'Skin-to-skin contact immediately after birth helps regulate baby\'s temperature, heart rate, and breathing. It promotes bonding, supports successful breastfeeding initiation, and helps stabilize blood sugar levels. Research shows that babies who experience immediate skin-to-skin are calmer, cry less, and are more likely to breastfeed successfully. The first hour after birth, often called the "golden hour," is an especially powerful time for this contact.',
    icon: 'Heart',
    allowCustom: true,
    options: [
      { value: 'immediate', label: 'Immediately, uninterrupted', birthPlanText: 'Please place baby directly on my chest for immediate skin-to-skin contact. We want this to be uninterrupted for at least the first hour.', isPopular: true, icon: 'Heart' },
      { value: 'after_assessment', label: 'After initial assessment', birthPlanText: 'We would like skin-to-skin after the initial newborn assessment.', icon: 'Clock' },
      { value: 'partner_backup', label: 'Partner does skin-to-skin if I can\'t', birthPlanText: 'If I am unable to do skin-to-skin immediately (such as during a C-section), please place baby skin-to-skin with my partner.', isPopular: true, icon: 'Users' },
    ],
  },
  {
    id: 'cord_clamping',
    sectionId: 'at_birth',
    title: 'Cord Clamping Timing',
    description: 'Delaying cord clamping for 1-3 minutes (or longer) allows more blood to transfer from the placenta to your baby. This extra blood provides additional iron stores that can last for the first 6 months of life, reducing the risk of anemia. It also helps with baby\'s transition to breathing on their own and supports cardiovascular stability. The World Health Organization recommends waiting at least 1-3 minutes before clamping, and many providers now consider this standard practice.',
    icon: 'Link',
    allowCustom: true,
    quizQuestionId: 'cord_clamping',
    options: [
      { value: '1min', label: 'Wait at least 90 seconds', birthPlanText: 'Please wait at least 90 seconds before clamping the cord.', isPopular: true, icon: 'Clock' },
      { value: '3-5min', label: 'Wait 5 minutes', birthPlanText: 'Please delay cord clamping for 5 minutes.', isPopular: true, icon: 'Clock' },
      { value: 'until_stops', label: 'Wait until cord stops pulsing', birthPlanText: 'Please wait until the cord stops pulsing before clamping.', icon: 'Clock' },
      { value: 'lotus', label: 'Lotus birth (cord falls off naturally)', birthPlanText: 'We plan a lotus birth - please do not cut the cord. We will allow it to detach naturally.', icon: 'Leaf' },
      { value: 'immediate', label: 'Clamp right away', birthPlanText: 'We are comfortable with immediate cord clamping.', icon: 'Scissors' },
    ],
  },
  {
    id: 'who_cuts_cord',
    sectionId: 'at_birth',
    title: 'Who Cuts the Cord',
    description: 'Who will cut the umbilical cord',
    icon: 'Scissors',
    allowCustom: true,
    options: [
      { value: 'partner', label: 'Partner cuts the cord', birthPlanText: 'My partner would like to cut the umbilical cord.', isPopular: true },
      { value: 'mother', label: 'I want to cut the cord myself', birthPlanText: 'I would like to cut the cord myself.' },
      { value: 'provider', label: 'Provider can cut it', birthPlanText: 'Our provider may cut the umbilical cord.' },
    ],
  },
  {
    id: 'cord_blood_banking',
    sectionId: 'at_birth',
    title: 'Cord Blood Banking',
    description: 'Collecting and storing cord blood',
    icon: 'Database',
    allowCustom: true,
    quizQuestionId: 'cord_blood',
    options: [
      { value: 'private', label: 'Private banking (for our family)', birthPlanText: 'We will be privately banking cord blood.' },
      { value: 'public', label: 'Donate to a public bank', birthPlanText: 'We would like to donate cord blood to a public bank if available.' },
      { value: 'no', label: 'No cord blood banking', birthPlanText: 'We do not plan to bank or donate cord blood.', isPopular: true },
    ],
  },
  {
    id: 'placenta',
    sectionId: 'at_birth',
    title: 'Placenta Plans',
    description: 'What to do with the placenta',
    icon: 'Leaf',
    allowCustom: true,
    quizQuestionId: 'placenta',
    options: [
      { value: 'dispose', label: 'Hospital disposal is fine', birthPlanText: 'The hospital may dispose of the placenta.', isPopular: true },
      { value: 'encapsulate', label: 'Keep for encapsulation', birthPlanText: 'We will be keeping the placenta for encapsulation. Please place it in our provided container.', isPopular: true },
      { value: 'keep', label: 'Keep for other purposes', birthPlanText: 'We would like to keep the placenta for other reasons.' },
    ],
  },
  {
    id: 'physiological_placenta',
    sectionId: 'at_birth',
    title: 'Placenta Delivery',
    description: 'Third stage management - how the placenta is delivered',
    icon: 'Clock',
    allowCustom: true,
    clinical: true,
    quizQuestionId: 'placenta_delivery',
    options: [
      { value: 'physiological', label: 'Natural separation, no traction', birthPlanText: 'We prefer physiological delivery of the placenta - allowing time for natural separation without cord traction.', isPopular: true },
      { value: 'natural_with_pitocin', label: 'Natural + Pitocin for hemorrhage prevention', birthPlanText: 'We prefer natural placenta delivery but are open to Pitocin after delivery to reduce hemorrhage risk.' },
      { value: 'active_management', label: 'Active management (Pitocin + gentle traction)', birthPlanText: 'Active management of the third stage is fine, including routine Pitocin and gentle cord traction.' },
      { value: 'provider_standard', label: 'Provider\'s standard protocol', birthPlanText: '' },
    ],
  },
  {
    id: 'see_placenta',
    sectionId: 'at_birth',
    title: 'See the Placenta',
    description: 'Viewing the placenta after birth',
    icon: 'Eye',
    allowCustom: true,
    options: [
      { value: 'yes', label: 'Yes', birthPlanText: 'We would like to see and examine the placenta.' },
      { value: 'no', label: 'No', birthPlanText: 'We do not need to see the placenta.' },
    ],
  },
  {
    id: 'golden_hour',
    sectionId: 'at_birth',
    title: 'The Golden Hour',
    description: 'The first hour after birth is called the "golden hour" because it\'s a uniquely powerful time for bonding and establishing breastfeeding. When given uninterrupted skin-to-skin contact, babies naturally progress through stages that lead to self-attachment and their first feeding. During this time, baby is in a quiet alert state, taking in your smell, sound, and warmth. Routine procedures like weighing, measuring, and bathing can wait without any medical risk, and protecting this time can set the stage for successful breastfeeding and secure attachment.',
    icon: 'Sun',
    allowCustom: true,
    quizQuestionId: 'golden_hour',
    options: [
      { value: 'protected', label: 'Protect it fully - no interruptions', birthPlanText: 'We want the first hour after birth to be uninterrupted skin-to-skin time. Please delay all non-urgent procedures.', isPopular: true },
      { value: 'flexible', label: 'Flexible timing', birthPlanText: 'We are flexible about timing of assessments and procedures.' },
    ],
  },
  {
    id: 'sex_announcement',
    sectionId: 'at_birth',
    title: 'Baby\'s Sex Announcement',
    description: 'Who announces baby\'s sex at delivery',
    icon: 'Sparkles',
    allowCustom: true,
    quizQuestionId: 'sex_announcement',
    options: [
      { value: 'discover_ourselves', label: 'We discover ourselves', birthPlanText: 'Please allow us to discover baby\'s sex ourselves - do not announce it.' },
      { value: 'partner_announces', label: 'Partner announces', birthPlanText: 'We would like my partner to announce baby\'s sex.' },
      { value: 'provider_announces', label: 'Provider announces', birthPlanText: 'Our provider may announce baby\'s sex at delivery.' },
    ],
  },
  {
    id: 'first_feeding',
    sectionId: 'at_birth',
    title: 'First Feeding',
    description: 'Initiating breastfeeding or bottle feeding',
    icon: 'Baby',
    allowCustom: true,
    options: [
      { value: 'immediate_breast', label: 'Immediate breastfeeding', birthPlanText: 'I would like to initiate breastfeeding within the first hour.', isPopular: true },
      { value: 'when_ready', label: 'When baby shows cues', birthPlanText: 'We will feed baby when showing hunger cues.' },
      { value: 'bottle', label: 'Bottle feeding', birthPlanText: 'We will be bottle feeding from the start.' },
    ],
  },

  // ============================================
  // NEWBORN PROCEDURES
  // ============================================
  {
    id: 'vitamin_k',
    sectionId: 'newborn_procedures',
    title: 'Vitamin K Shot',
    description: 'Vitamin K helps with blood clotting and prevents a rare but serious bleeding disorder called Vitamin K Deficiency Bleeding (VKDB). Newborns are born with very low levels of vitamin K because it doesn\'t cross the placenta easily and isn\'t in breast milk in sufficient amounts. The single injection at birth provides protection for the first few months of life. VKDB can cause bleeding in the brain or internal organs and can be life-threatening. The injection is recommended by the American Academy of Pediatrics.',
    icon: 'Syringe',
    allowCustom: true,
    clinical: true,
    quizQuestionId: 'vitamin_k',
    options: [
      { value: 'accept', label: 'Yes, give the Vitamin K shot', birthPlanText: 'Please give the Vitamin K injection as recommended.', isPopular: true, icon: 'Shield', defaultStance: 'desired' },
      { value: 'oral', label: 'Oral Vitamin K - We have confirmed that our birth facility offers this', birthPlanText: 'We prefer oral Vitamin K administration over the injection. We understand the hospital offers this.', icon: 'Pill', defaultStance: 'cautious' },
      { value: 'oral_own', label: 'Oral Vitamin K - We will bring our own to administer ourselves', birthPlanText: 'We prefer oral Vitamin K and will bring our own supply.', icon: 'Package', defaultStance: 'cautious' },
      { value: 'decline', label: 'We decline', birthPlanText: 'We decline the Vitamin K injection at this time.', icon: 'AlertCircle', defaultStance: 'declined' },
    ],
  },
  {
    id: 'eye_ointment',
    sectionId: 'newborn_procedures',
    title: 'Eye Ointment (Erythromycin)',
    description: 'Antibiotic eye ointment is applied to prevent serious eye infections that could be transmitted during birth, particularly gonorrhea and chlamydia. These infections can cause blindness if left untreated. The ointment is typically applied within the first hour after birth and is required by law in many states. Some parents prefer to delay it briefly to allow for initial eye contact and bonding, which is often an acceptable compromise. The ointment can cause temporary blurry vision for baby but is not painful.',
    icon: 'Eye',
    allowCustom: true,
    clinical: true,
    quizQuestionId: 'eye_ointment',
    options: [
      { value: 'accept', label: 'Yes, apply the ointment', birthPlanText: 'Please apply the erythromycin eye ointment as recommended.', isPopular: true, defaultStance: 'desired' },
      { value: 'delay', label: 'Delay for bonding first', birthPlanText: 'Please delay the eye ointment to allow for initial bonding and breastfeeding.', isPopular: true, defaultStance: 'cautious' },
      { value: 'decline', label: 'We decline', birthPlanText: 'We decline the erythromycin eye ointment.', defaultStance: 'declined' },
    ],
  },
  {
    id: 'hep_b_vaccine',
    sectionId: 'newborn_procedures',
    title: 'Hepatitis B Vaccine',
    description: 'First dose typically given within 24 hours',
    icon: 'Shield',
    allowCustom: true,
    clinical: true,
    quizQuestionId: 'hep_b_vaccine',
    options: [
      { value: 'accept', label: 'Yes, give at birth', birthPlanText: 'Please administer the Hepatitis B vaccine at birth.', defaultStance: 'desired' },
      { value: 'delay', label: 'Delay until pediatrician visit', birthPlanText: 'We prefer to delay the Hepatitis B vaccine until our pediatrician visit.', isPopular: true, defaultStance: 'cautious' },
      { value: 'decline', label: 'We decline', birthPlanText: 'We decline the Hepatitis B vaccine at this time.', defaultStance: 'declined' },
    ],
  },
  {
    id: 'newborn_screening',
    sectionId: 'newborn_procedures',
    title: 'Newborn Screening (Heel Prick)',
    description: 'Blood test for genetic conditions',
    icon: 'TestTube',
    allowCustom: true,
    clinical: true,

    options: [
      { value: 'accept', label: 'Yes, do the screening', birthPlanText: 'Please perform the standard newborn screening tests.', isPopular: true, defaultStance: 'desired' },
      { value: 'decline', label: 'We decline', birthPlanText: 'We decline the newborn screening tests.', defaultStance: 'declined' },
    ],
  },
  {
    id: 'hearing_test',
    sectionId: 'newborn_procedures',
    title: 'Hearing Test',
    description: 'Quick, painless hearing screening',
    icon: 'Activity',
    allowCustom: true,
    clinical: true,

    options: [
      { value: 'accept', label: 'Yes, do the hearing test', birthPlanText: 'Please perform the newborn hearing screening.', isPopular: true, defaultStance: 'desired' },
      { value: 'decline', label: 'We decline', birthPlanText: 'We decline the hearing screening at this time.', defaultStance: 'declined' },
    ],
  },
  {
    id: 'bath_timing',
    sectionId: 'newborn_procedures',
    title: 'First Bath Timing',
    description: 'Delaying your baby\'s first bath has several benefits. The creamy white coating on newborns (vernix) is a natural moisturizer and provides antibacterial protection. Babies are also born with their mother\'s scent, which helps with bonding and breastfeeding. Bathing too soon can cause temperature instability and may disrupt the first feeding. The World Health Organization recommends waiting at least 24 hours before the first bath, and many experts suggest waiting even longer. When you do bathe baby, warm sponge baths are gentler than full immersion until the umbilical cord falls off.',
    icon: 'Bath',
    allowCustom: true,
    quizQuestionId: 'bath_timing',
    options: [
      { value: '24hrs', label: 'Delay at least 24 hours', birthPlanText: 'Please delay baby\'s first bath for at least 24 hours.', isPopular: true },
      { value: '48hrs', label: 'Delay at least 48 hours', birthPlanText: 'Please delay baby\'s first bath for at least 48 hours.', isPopular: true },
      { value: 'parents_only', label: 'We want to give the first bath at home', birthPlanText: 'We would like to give baby\'s first bath ourselves at home.' },
      { value: 'hospital_recommend', label: 'Whenever the hospital recommends', birthPlanText: 'Baby\'s first bath may be given when recommended by nursing staff.' },
    ],
  },
  {
    id: 'circumcision',
    sectionId: 'newborn_procedures',
    title: 'Circumcision (if applicable)',
    description: 'For baby boys',
    icon: 'Baby',
    allowCustom: true,
    clinical: true,
    quizQuestionId: 'circumcision',
    options: [
      { value: 'yes', label: 'Yes, circumcise at the hospital', birthPlanText: 'We would like our son circumcised before leaving the hospital.', icon: 'Shield', defaultStance: 'desired' },
      { value: 'delayed', label: 'Yes, but by our own provider later', birthPlanText: 'We will arrange circumcision with our own provider after discharge.', icon: 'Clock' },
      { value: 'no', label: 'No circumcision', birthPlanText: 'We do not want circumcision performed.', isPopular: true, icon: 'AlertCircle', defaultStance: 'declined' },
      { value: 'na', label: 'Not applicable', birthPlanText: '', icon: 'Circle' },
    ],
  },
  {
    id: 'procedure_timing',
    sectionId: 'newborn_procedures',
    title: 'Timing of Procedures',
    description: 'When non-urgent procedures are performed',
    icon: 'Clock',
    allowCustom: true,
    options: [
      { value: 'delay_golden_hour', label: 'Delay all until after the golden hour', birthPlanText: 'Please delay all non-urgent procedures until after the first hour to allow for bonding and first feeding.', isPopular: true },
      { value: 'ask_first', label: 'Ask us before each procedure', birthPlanText: 'Please ask our permission before each procedure and explain what will be done.' },
      { value: 'standard', label: 'Standard timing', birthPlanText: 'Standard timing for procedures is acceptable.' },
    ],
  },
  {
    id: 'infant_pain_management',
    sectionId: 'newborn_procedures',
    title: 'Baby\'s Comfort During Procedures',
    description: 'Pain management for newborn procedures',
    icon: 'Heart',
    allowCustom: true,
    clinical: true,
    quizQuestionId: 'infant_pain_management',
    options: [
      { value: 'breastfeed_during', label: 'Breastfeed during procedures', birthPlanText: 'Please allow me to breastfeed baby during procedures for comfort and pain relief.', isPopular: true, defaultStance: 'desired' },
      { value: 'skin_to_skin_during', label: 'Skin-to-skin during procedures', birthPlanText: 'Please perform newborn procedures during skin-to-skin contact when possible.', defaultStance: 'desired' },
      { value: 'sugar_water', label: 'Sugar water is fine', birthPlanText: 'Sugar water for pain management during procedures is fine with us.', defaultStance: 'desired' },
      { value: 'no_sugar_water', label: 'No sugar water', birthPlanText: 'Please do not give baby sugar water. We prefer breastfeeding or skin-to-skin for comfort.', defaultStance: 'declined' },
      { value: 'infant_tylenol', label: 'Infant Tylenol', birthPlanText: 'We are open to infant Tylenol (acetaminophen) for pain management after procedures if needed.' },
      { value: 'provider_choice', label: 'Provider\'s standard approach', birthPlanText: 'We are fine with the standard approach to infant comfort during procedures.' },
    ],
  },

  // ============================================
  // HOSPITAL STAY
  // ============================================
  {
    id: 'rooming_in',
    sectionId: 'hospital_stay',
    title: 'Rooming In',
    description: 'Rooming-in means keeping your baby in your hospital room instead of in the nursery. Research shows that rooming-in supports bonding, makes breastfeeding easier by allowing you to respond quickly to feeding cues, and helps you learn your baby\'s unique patterns. It also reduces the risk of hospital errors or mix-ups. However, it can be tiring for new parents who are recovering from birth. Many hospitals now encourage rooming-in but still offer nursery care when parents need rest.',
    icon: 'Home',
    allowCustom: true,
    hiddenForVenue: ['home', 'birth_center'],
    quizQuestionId: 'rooming_in',
    options: [
      { value: '24_7', label: 'Baby stays with us 24/7', birthPlanText: 'We want baby to room-in with us at all times.', isPopular: true, icon: 'Heart' },
      { value: 'nursery_option', label: 'Mostly with us, may use nursery for rest', birthPlanText: 'We prefer rooming-in but may use the nursery for rest periods.', isPopular: true, icon: 'Moon' },
    ],
  },
  {
    id: 'feeding_support',
    sectionId: 'hospital_stay',
    title: 'Feeding Support',
    description: 'Lactation and feeding assistance',
    icon: 'HeartHandshake',
    allowCustom: true,
    quizQuestionId: 'feeding',
    options: [
      { value: 'exclusive_breastfeed', label: 'Exclusive breastfeeding', birthPlanText: 'We plan to exclusively breastfeed. Please do not offer formula or pacifiers without our consent.', isPopular: true },
      { value: 'breastfeed', label: 'Breastfeed (open to supplementing)', birthPlanText: 'We plan to breastfeed our baby.' },
      { value: 'formula', label: 'Formula feed', birthPlanText: 'We plan to use formula.' },
      { value: 'donor_milk', label: 'Donor milk if supplementation needed', birthPlanText: 'If supplementation is needed, we prefer donor milk over formula.' },
      { value: 'no_formula_without_consent', label: 'No formula without consent', birthPlanText: 'Please do not give formula without our explicit consent.' },
      { value: 'lactation_consultant', label: 'Lactation consultant requested', birthPlanText: 'We would like a lactation consultant visit during our hospital stay.' },
      { value: 'flexible', label: 'Flexible', birthPlanText: 'We are flexible about feeding and open to whatever works best.' },
    ],
  },
  {
    id: 'pacifier',
    sectionId: 'hospital_stay',
    title: 'Pacifier Use',
    description: 'Whether to offer pacifiers',
    icon: 'Circle',
    allowCustom: true,
    clinical: true,
    quizQuestionId: 'pacifier',
    options: [
      { value: 'no', label: 'No pacifiers please', birthPlanText: 'Please do not give baby a pacifier.', isPopular: true, icon: 'AlertCircle', defaultStance: 'declined' },
      { value: 'if_needed', label: "Flexible, we'll see", birthPlanText: "We're flexible, if it seems needed then we'd be open to using pacifiers after a discussion.", icon: 'ArrowLeftRight' },
      { value: 'yes', label: 'Pacifiers are fine with us', birthPlanText: 'We plan to use pacifiers.', icon: 'Shield', defaultStance: 'desired' },
    ],
  },
  {
    id: 'visitors',
    sectionId: 'hospital_stay',
    title: 'Visitor Policy',
    description: 'Who can visit and when',
    icon: 'Users',
    allowCustom: true,
    quizQuestionId: 'visitors',
    options: [
      { value: 'open', label: 'Visitors are welcome anytime', birthPlanText: 'We welcome visitors during our hospital stay.' },
      { value: 'limited', label: 'Close family only, limited hours', birthPlanText: 'We prefer brief visits from close family only during limited hours.', isPopular: true },
      { value: 'no_visitors', label: 'No visitors until we\'re home', birthPlanText: 'We prefer no visitors at the hospital. We will welcome visitors once we are settled at home.', isPopular: true },
    ],
  },
  {
    id: 'length_of_stay',
    sectionId: 'hospital_stay',
    title: 'Length of Stay',
    description: 'Preference for hospital stay duration',
    icon: 'Calendar',
    allowCustom: true,
    hiddenForVenue: ['home', 'birth_center'],
    options: [
      { value: 'minimum', label: 'Leave as soon as possible', birthPlanText: 'We prefer to be discharged as soon as safely possible.', isPopular: true },
      { value: 'standard', label: 'Standard stay', birthPlanText: 'We are comfortable with the standard length of stay.' },
      { value: 'extended', label: 'Extended if we need support', birthPlanText: 'We would like to stay longer if we feel we need more support.' },
    ],
  },
  {
    id: 'quiet_environment',
    sectionId: 'hospital_stay',
    title: 'Room Environment',
    description: 'Preferences for room atmosphere',
    icon: 'Moon',
    allowCustom: true,
    options: [
      { value: 'quiet', label: 'Quiet and minimal interruptions', birthPlanText: 'We prefer a quiet environment with minimal interruptions for rest and bonding.', isPopular: true },
      { value: 'standard', label: 'Standard hospital routine', birthPlanText: 'Standard hospital routine and check-ins are fine.' },
    ],
  },
  {
    id: 'formula_supplementation',
    sectionId: 'hospital_stay',
    title: 'Formula Supplementation',
    description: 'Whether formula can be given if baby has minimal weight gain',
    icon: 'Baby',
    allowCustom: true,
    clinical: true,
    options: [
      { value: 'open', label: 'Open to formula if needed for weight gain', birthPlanText: 'We are open to formula supplementation if baby is not gaining weight adequately.', defaultStance: 'desired' },
      { value: 'breastmilk_only', label: 'Breastmilk only, no formula', birthPlanText: 'Please do not supplement with formula without our explicit consent.', defaultStance: 'declined' },
      { value: 'discuss_first', label: 'Discuss with us before supplementing', birthPlanText: 'Please discuss any formula supplementation with us before offering it.', defaultStance: 'cautious' },
    ],
  },
  {
    id: 'lactation_support',
    sectionId: 'hospital_stay',
    title: 'Lactation Support',
    description: 'Requesting lactation consultant support',
    icon: 'Users',
    allowCustom: true,
    options: [
      { value: 'request_visit', label: 'Request lactation consultant visit', birthPlanText: 'We would like a lactation consultant visit during our hospital stay.', isPopular: true },
      { value: 'if_needed', label: 'If we need help', birthPlanText: 'Please make a lactation consultant available if we are having difficulty with breastfeeding.' },
      { value: 'not_needed', label: 'No LC needed', birthPlanText: 'We do not need a lactation consultant visit.' },
    ],
  },
  {
    id: 'baby_companion',
    sectionId: 'hospital_stay',
    title: 'If Baby Needs to Leave',
    description: 'Who accompanies baby if separated',
    icon: 'Users',
    allowCustom: true,
    quizQuestionId: 'baby_companion',
    options: [
      { value: 'partner_always', label: 'Partner stays with baby', birthPlanText: 'If baby must leave our room, my partner should accompany baby at all times.', isPopular: true },
      { value: 'someone_present', label: 'Support person with baby', birthPlanText: 'We request that a support person be present with baby during any procedures or transfers.' },
      { value: 'flexible', label: 'Flexible', birthPlanText: 'We are flexible about who accompanies baby.' },
    ],
  },
  {
    id: 'transfer_plan',
    sectionId: 'hospital_stay',
    title: 'Backup Hospital',
    description: 'Which hospital you would transfer to if needed',
    icon: 'Building2',
    allowCustom: true,
    venueOnly: ['home', 'birth_center'],
    quizQuestionId: 'transfer_plan',
    options: [
      { value: 'has_plan', label: 'We have a backup hospital chosen', birthPlanText: '' },
      { value: 'no_backup', label: 'No backup facility chosen yet', birthPlanText: 'We have not yet chosen a backup hospital.' },
      { value: 'researching', label: 'I need to research backup options', birthPlanText: 'We are still researching backup hospital options.' },
    ],
  },
  {
    id: 'transfer_logistics',
    sectionId: 'hospital_stay',
    title: 'Transfer Transportation',
    description: 'How you plan to get to the hospital if transfer is needed',
    icon: 'Navigation',
    allowCustom: true,
    venueOnly: ['home', 'birth_center'],
    quizQuestionId: 'transfer_logistics',
    options: [
      { value: 'partner_drives', label: 'Partner will drive', birthPlanText: 'If transfer is needed, my partner will drive us to the hospital.' },
      { value: 'ambulance', label: 'Call an ambulance', birthPlanText: 'If transfer is needed, please call an ambulance for transport.' },
      { value: 'midwife_decides', label: 'Midwife helps decide', birthPlanText: 'Our midwife will help determine the best transport method if transfer is needed.' },
    ],
  },
  {
    id: 'transfer_labor_prefs',
    sectionId: 'hospital_stay',
    title: 'Hospital Labor Preferences',
    description: 'Your preferences if you end up laboring at the hospital',
    icon: 'Shield',
    allowCustom: true,
    venueOnly: ['home', 'birth_center'],
    quizQuestionId: 'hospital_labor_contingency',
    options: [
      { value: 'epidural_open', label: 'Open to epidural', birthPlanText: 'If transferred, we are open to an epidural for pain management.' },
      { value: 'epidural_decline', label: 'Prefer no epidural', birthPlanText: 'If transferred, we prefer to continue without an epidural unless medically necessary.' },
      { value: 'heplock', label: 'Hep-lock IV only', birthPlanText: 'If transferred, we prefer a hep-lock for IV access rather than continuous fluids.' },
      { value: 'intermittent_monitor', label: 'Request intermittent monitoring', birthPlanText: 'If transferred, we prefer intermittent fetal monitoring if the clinical situation allows.' },
      { value: 'no_students', label: 'No medical students', birthPlanText: 'If transferred, we do not want medical students or observers present.' },
    ],
  },
  {
    id: 'transfer_newborn_prefs',
    sectionId: 'hospital_stay',
    title: 'Newborn Procedures at Hospital',
    description: 'Your preferences for newborn procedures if you transfer to a hospital',
    icon: 'Baby',
    allowCustom: true,
    venueOnly: ['home', 'birth_center'],
    quizQuestionId: 'hospital_newborn_contingency',
    options: [
      { value: 'delayed_cord', label: 'Delayed cord clamping', birthPlanText: 'We request delayed cord clamping even if in the hospital.' },
      { value: 'skin_to_skin', label: 'Immediate skin-to-skin if baby is stable', birthPlanText: 'We request immediate skin-to-skin contact if baby is stable.' },
      { value: 'delay_bath', label: 'Delay baby\'s first bath', birthPlanText: 'Please delay baby\'s first bath.' },
      { value: 'delay_exams', label: 'Delay non-urgent newborn exams for bonding', birthPlanText: 'We request that non-urgent newborn exams be delayed for bonding time.' },
      { value: 'eye_ointment_delay', label: 'Delay eye ointment for bonding', birthPlanText: 'We request eye ointment be delayed to allow for initial bonding.' },
      { value: 'vitamin_k_yes', label: 'Administer vitamin K injection', birthPlanText: 'Please administer the vitamin K injection.' },
      { value: 'no_formula', label: 'No formula without discussion', birthPlanText: 'Please do not give formula without discussing with us first.' },
    ],
  },
  {
    id: 'transfer_stay_prefs',
    sectionId: 'hospital_stay',
    title: 'Hospital Stay Preferences',
    description: 'Your preferences if you stay at the hospital after birth',
    icon: 'Building',
    allowCustom: true,
    venueOnly: ['home', 'birth_center'],
    quizQuestionId: 'hospital_stay_contingency',
    options: [
      { value: 'rooming_in', label: 'Baby rooms in with us', birthPlanText: 'If at the hospital, we want baby to room in with us at all times.' },
      { value: 'discharge_asap', label: 'Discharge as soon as medically safe', birthPlanText: 'If at the hospital, we would like to be discharged as soon as it is medically safe.' },
      { value: 'breastfeeding_support', label: 'Request lactation/breastfeeding support', birthPlanText: 'If at the hospital, we would like lactation consultant support.' },
      { value: 'quiet_recovery', label: 'Request a quiet recovery environment', birthPlanText: 'If at the hospital, we prefer a quiet recovery environment with minimal disruptions.' },
      { value: 'visitor_limits', label: 'Limit visitors', birthPlanText: 'If at the hospital, we prefer limited visitors during our recovery.' },
      { value: 'skin_to_skin_continue', label: 'Continue skin-to-skin as much as possible', birthPlanText: 'If at the hospital, we want to continue skin-to-skin contact as much as possible.' },
    ],
  },

  // ============================================
  // C-SECTION (if needed)
  // ============================================
  {
    id: 'gentle_csection',
    sectionId: 'csection',
    title: 'Gentle C-Section Techniques',
    description: 'Family-centered approach to cesarean',
    icon: 'Heart',
    allowCustom: true,
    quizQuestionId: 'csection_approach',
    options: [
      { value: 'yes', label: 'Gentle/family-centered C-section', birthPlanText: 'If a C-section is needed, we would like a gentle, family-centered approach: clear drape, immediate skin-to-skin in the OR, and delayed cord clamping when safely possible.', isPopular: true },
      { value: 'discuss', label: 'Standard, but with some preferences', birthPlanText: 'If a C-section is needed, we would like to discuss specific preferences with our surgical team, such as partner presence and music.' },
      { value: 'standard', label: 'Follow the medical team\'s lead', birthPlanText: 'If a C-section becomes necessary, we trust the medical team to follow standard protocols.' },
    ],
  },
  {
    id: 'clear_drape',
    sectionId: 'csection',
    title: 'Clear Drape',
    description: 'Ability to see baby being born',
    icon: 'Eye',
    allowCustom: true,

    options: [
      { value: 'yes', label: 'Clear drape or lower at birth', birthPlanText: 'We would like a clear drape or to have the drape lowered so we can see baby being born.', isPopular: true },
      { value: 'no', label: 'Standard drape', birthPlanText: 'Standard drape is fine; we prefer not to watch the procedure.' },
    ],
  },
  {
    id: 'csection_skin_to_skin',
    sectionId: 'csection',
    title: 'Skin-to-Skin in OR',
    description: 'Immediate contact during C-section',
    icon: 'Heart',
    allowCustom: true,

    options: [
      { value: 'immediate', label: 'Immediate in OR', birthPlanText: 'Please place baby skin-to-skin with me in the operating room as soon as possible.', isPopular: true },
      { value: 'recovery', label: 'In recovery room', birthPlanText: 'We would like skin-to-skin contact to begin in the recovery room.' },
      { value: 'partner', label: 'Partner can do skin-to-skin', birthPlanText: 'My partner can do skin-to-skin in the OR while I am being closed.', isPopular: true },
    ],
  },
  {
    id: 'csection_music',
    sectionId: 'csection',
    title: 'Music During Surgery',
    description: 'Playing your own music',
    icon: 'Music',
    allowCustom: true,

    options: [
      { value: 'yes', label: 'We will bring music', birthPlanText: 'We would like to play our own music during the delivery.', isPopular: true },
      { value: 'no', label: 'No music needed', birthPlanText: 'No specific music preferences.' },
    ],
  },
  {
    id: 'csection_photos',
    sectionId: 'csection',
    title: 'Photos/Video During C-Section',
    description: 'Documenting the birth',
    icon: 'Camera',
    allowCustom: true,

    options: [
      { value: 'yes', label: 'Photos and/or video', birthPlanText: 'We would like to take photos and/or video during the birth.', isPopular: true },
      { value: 'photos_only', label: 'Photos only', birthPlanText: 'We would like to take photos but not video.' },
      { value: 'no', label: 'No photos or video', birthPlanText: 'We prefer no photos or video during the procedure.' },
    ],
  },
  {
    id: 'partner_presence_csection',
    sectionId: 'csection',
    title: 'Partner Presence',
    description: 'Partner in operating room',
    icon: 'Users',
    allowCustom: true,
    options: [
      { value: 'required', label: 'Partner must be present', birthPlanText: 'It is very important that my partner be present during the C-section.', isPopular: true },
      { value: 'preferred', label: 'Partner preferred', birthPlanText: 'We would like my partner to be present if possible.' },
    ],
  },
  {
    id: 'csection_delayed_cord',
    sectionId: 'csection',
    title: 'Delayed Cord Clamping',
    description: 'Timing of cord clamping during cesarean',
    icon: 'Clock',
    allowCustom: true,
    options: [
      { value: 'yes', label: 'Request delayed clamping', birthPlanText: 'During a C-section, please delay cord clamping for at least 60 seconds.', isPopular: true },
      { value: 'standard', label: 'Follow surgeon\'s protocol', birthPlanText: 'We are comfortable with the surgeon\'s standard cord clamping protocol during a C-section.' },
    ],
  },
  {
    id: 'csection_explanation',
    sectionId: 'csection',
    title: 'Communication During Procedure',
    description: 'Updates during surgery',
    icon: 'MessageSquare',
    allowCustom: true,
    options: [
      { value: 'narrate', label: 'Explain what\'s happening', birthPlanText: 'Please explain what is happening during the procedure.', isPopular: true },
      { value: 'minimal', label: 'Minimal talking', birthPlanText: 'We prefer a quiet environment with minimal talking unless necessary.' },
    ],
  },
  {
    id: 'csection_arm_mobility',
    sectionId: 'csection',
    title: 'Arm Mobility During Surgery',
    description: 'Freedom of arm movement',
    icon: 'Move',
    allowCustom: true,
    options: [
      { value: 'not_strapped', label: 'Prefer not strapped down', birthPlanText: 'I prefer to have my arms free and not strapped down during the C-section.', isPopular: true },
      { value: 'standard', label: 'Standard procedure fine', birthPlanText: 'Standard arm positioning is acceptable.' },
    ],
  },
  {
    id: 'csection_environment',
    sectionId: 'csection',
    title: 'C-Section Environment',
    description: 'Ambiance preferences for the operating room',
    icon: 'Moon',
    allowCustom: true,
    options: [
      { value: 'dim_quiet', label: 'Low lighting and quiet voices', birthPlanText: 'We would appreciate low lighting and quiet voices in the operating room.' },
      { value: 'standard', label: 'Standard environment', birthPlanText: 'Standard operating room environment is fine.' },
    ],
  },
  {
    id: 'doula_presence_csection',
    sectionId: 'csection',
    title: 'Doula During C-Section',
    description: 'Whether your doula will be present during surgery',
    icon: 'UserCheck',
    allowCustom: true,
    options: [
      { value: 'yes', label: 'Doula present throughout', birthPlanText: 'Our doula should be present in the operating room throughout the procedure.' },
      { value: 'no', label: 'No doula during surgery', birthPlanText: 'Our doula will not be present during the surgery.' },
    ],
  },
  {
    id: 'vaginal_seeding',
    sectionId: 'csection',
    title: 'Vaginal Seeding',
    description: 'Swabbing baby with maternal vaginal bacteria after C-section to support microbiome colonization. Requires screening for active infections beforehand.',
    icon: 'Droplets',
    allowCustom: true,
    clinical: true,
    quizQuestionId: 'csection_vaginal_seeding',
    options: [
      { value: 'yes', label: 'Yes, we plan to do vaginal seeding', birthPlanText: 'We plan to perform vaginal seeding after the C-section to support baby\'s microbiome.', isPopular: true },
      { value: 'discuss', label: 'Interested but want to discuss with provider', birthPlanText: 'We are interested in vaginal seeding and would like to discuss it with our provider before making a decision.', defaultStance: 'cautious' },
      { value: 'no', label: 'No, not for us', birthPlanText: 'We do not plan to do vaginal seeding.' },
    ],
  },
  {
    id: 'avoid_general_anesthesia',
    sectionId: 'csection',
    title: 'Avoid General Anesthesia',
    description: 'Preference for regional anesthesia',
    icon: 'Shield',
    allowCustom: true,
    clinical: true,
    options: [
      { value: 'strongly_prefer_regional', label: 'Strongly prefer regional', birthPlanText: 'I strongly prefer regional anesthesia (spinal or epidural) over general anesthesia if safely possible.', isPopular: true },
      { value: 'open_to_needed', label: 'Open to what\'s needed', birthPlanText: 'I am open to whatever anesthesia type is medically appropriate.' },
    ],
  },
  {
    id: 'partner_catches_baby_csection',
    sectionId: 'csection',
    title: 'Partner Catches Baby (if possible)',
    description: 'Partner assistance in delivery',
    icon: 'Users',
    allowCustom: true,
    options: [
      { value: 'yes', label: 'Yes', birthPlanText: 'If possible and safe, we would like my partner to help catch/receive baby during the C-section.' },
      { value: 'no', label: 'No', birthPlanText: 'Standard delivery by medical team is preferred.' },
    ],
  },
]

// Helper function to get preferences by section
export function getPreferencesBySection(sectionId: string, birthType?: BirthType, venue?: BirthVenue | null): PreferenceDefinition[] {
  return PREFERENCES.filter(p => {
    if (p.sectionId !== sectionId) return false
    if (birthType && p.hiddenFor?.includes(birthType)) return false
    if (venue && p.hiddenForVenue?.includes(venue)) return false
    if (venue && p.venueOnly && !p.venueOnly.includes(venue)) return false
    return true
  })
}

// Helper function to get preference by ID
export function getPreferenceById(preferenceId: string): PreferenceDefinition | undefined {
  return PREFERENCES.find(p => p.id === preferenceId)
}

// Get default preference values for a section
// Initializes all preferences with their first "popular" option or first option
export function getDefaultPreferencesForSection(sectionId: string): Array<{
  preferenceId: string
  selectedOption: string | null
  isOmitted: boolean
  sortOrder: number
}> {
  const prefs = getPreferencesBySection(sectionId)
  return prefs.map((pref, index) => {
    // Find first popular option, or first option
    const defaultOption = pref.options.find(o => o.isPopular) || pref.options[0]
    return {
      preferenceId: pref.id,
      selectedOption: defaultOption?.value || null,
      isOmitted: pref.isOmittedByDefault || false,
      sortOrder: index,
    }
  })
}
